spring:
  application:
    name: sirapopb_api

  datasource:
    url: jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=Asia/Bangkok
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000

server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
